# Generated by Django 4.2.7 on 2024-02-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_review', '0002_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
